

development:
  adapter: postgresql
  encoding: utf-8
  database: prac
  host: localhost
  username: tamilarasan
  password: tamil
  port: 5432


production:
  adapter: postgresql
  encoding: utf-8
  database: prac
  host: localhost
  username: tamilarasan
  password: tamil
  port: 5432
